/*******************************************************************************
* Copyright (c) 2009, 2011 Overture Team and others.
*
* Overture is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* Overture is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Overture.  If not, see <http://www.gnu.org/licenses/>.
*
* The Overture Tool web-site: http://overturetool.org/
*******************************************************************************/

/* This file was generated by ASTcreator (http://www.lausdahl.com/). */

package org.destecs.script.ast.preprocessing;


import org.destecs.script.ast.analysis.intf.IAnalysis;
import java.util.Map;
import org.destecs.script.ast.analysis.intf.IQuestion;
import org.destecs.script.ast.node.INode;
import java.lang.String;
import org.destecs.script.ast.preprocessing.PIncludeBase;
import org.destecs.script.ast.preprocessing.EInclude;
import org.destecs.script.ast.preprocessing.AScriptInclude;
import org.destecs.script.ast.analysis.intf.IAnswer;
import org.destecs.script.ast.analysis.intf.IQuestionAnswer;


/**
* Generated file by AST Creator
* @author Kenneth Lausdahl
*
*/
public class AScriptInclude extends PIncludeBase
{
	private static final long serialVersionUID = 1L;

	private String _filename;

	/**
	* Creates a new {@code AScriptInclude} node with the given nodes as children.
	* The basic child nodes are removed from their previous parents.
	* @param filename_ the {@link String} node for the {@code filename} child of this {@link AScriptInclude} node
	*/
	public AScriptInclude(String filename_)
	{
		super();
		this.setFilename(filename_);

	}


	/**
	 * Creates a new {@link AScriptInclude} node with no children.
	 */
	public AScriptInclude()
	{

	}





	/**
	 * Essentially this.toString().equals(o.toString()).
	**/
	@Override
	public boolean equals(Object o) {
	if (o != null && o instanceof AScriptInclude)
	 return toString().equals(o.toString());
	return false; }
	
	/**
	 * Returns a deep clone of this {@link AScriptInclude} node.
	 * @return a deep clone of this {@link AScriptInclude} node
	 */
	public AScriptInclude clone()
	{
		return new AScriptInclude(
			_filename
		);
	}


	/**
	 * Removes the {@link INode} {@code child} as a child of this {@link AScriptInclude} node.
	 * Do not call this method with any graph fields of this node. This will cause any child's
	 * with the same reference to be removed unintentionally or {@link RuntimeException}will be thrown.
	 * @param child the child node to be removed from this {@link AScriptInclude} node
	 * @throws RuntimeException if {@code child} is not a child of this {@link AScriptInclude} node
	 */
	public void removeChild(INode child)
	{
		throw new RuntimeException("Not a child.");
	}


	/**
	 * Creates a deep clone of this {@link AScriptInclude} node while putting all
	 * old node-new node relations in the map {@code oldToNewMap}.
	 * @param oldToNewMap the map filled with the old node-new node relation
	 * @return a deep clone of this {@link AScriptInclude} node
	 */
	public AScriptInclude clone(Map<INode,INode> oldToNewMap)
	{
		AScriptInclude node = new AScriptInclude(
			_filename
		);
		oldToNewMap.put(this, node);
		return node;
	}


	/**
	 * Returns the {@link EInclude} corresponding to the
	 * type of this {@link EInclude} node.
	 * @return the {@link EInclude} for this node
	 */
	@Override
	public EInclude kindPInclude()
	{
		return EInclude.SCRIPT;
	}



	public String toString()
	{
		return (_filename!=null?_filename.toString():this.getClass().getSimpleName());
	}


	/**
	 * Sets the {@code _filename} child of this {@link AScriptInclude} node.
	 * @param value the new {@code _filename} child of this {@link AScriptInclude} node
	*/
	public void setFilename(String value)
	{
		this._filename = value;
	}


	/**
	 * @return the {@link String} node which is the {@code _filename} child of this {@link AScriptInclude} node
	*/
	public String getFilename()
	{
		return this._filename;
	}


	/**
	* Calls the {@link IAnalysis#caseAScriptInclude(AScriptInclude)} of the {@link IAnalysis} {@code analysis}.
	* @param analysis the {@link IAnalysis} to which this {@link AScriptInclude} node is applied
	*/
	@Override
	public void apply(IAnalysis analysis)
	{
		analysis.caseAScriptInclude(this);
	}


	/**
	* Calls the {@link IAnswer#caseAScriptInclude(AScriptInclude)} of the {@link IAnswer} {@code caller}.
	* @param caller the {@link IAnswer} to which this {@link AScriptInclude} node is applied
	*/
	@Override
	public <A> A apply(IAnswer<A> caller)
	{
		return caller.caseAScriptInclude(this);
	}


	/**
	* Calls the {@link IQuestion#caseAScriptInclude(AScriptInclude, Object)} of the {@link IQuestion} {@code caller}.
	* @param caller the {@link IQuestion} to which this {@link AScriptInclude} node is applied
	* @param question the question provided to {@code caller}
	*/
	@Override
	public <Q> void apply(IQuestion<Q> caller, Q question)
	{
		caller.caseAScriptInclude(this, question);
	}


	/**
	* Calls the {@link IQuestionAnswer#caseAScriptInclude(AScriptInclude, Object)} of the {@link IQuestionAnswer} {@code caller}.
	* @param caller the {@link IQuestionAnswer} to which this {@link AScriptInclude} node is applied
	* @param question the question provided to {@code caller}
	*/
	@Override
	public <Q, A> A apply(IQuestionAnswer<Q, A> caller, Q question)
	{
		return caller.caseAScriptInclude(this, question);
	}



}
