/*******************************************************************************
* Copyright (c) 2009, 2011 Overture Team and others.
*
* Overture is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* Overture is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Overture.  If not, see <http://www.gnu.org/licenses/>.
*
* The Overture Tool web-site: http://overturetool.org/
*******************************************************************************/

/* This file was generated by ASTcreator (http://www.lausdahl.com/). */

package org.destecs.script.ast.expressions;


import org.destecs.script.ast.analysis.intf.IAnalysis;
import java.util.Map;
import java.lang.Boolean;
import org.destecs.script.ast.expressions.ESingleExp;
import org.destecs.script.ast.analysis.intf.IQuestion;
import org.destecs.script.ast.expressions.SSingleExpBase;
import org.destecs.script.ast.node.INode;
import java.lang.String;
import org.destecs.script.ast.analysis.intf.IAnswer;
import org.destecs.script.ast.analysis.intf.IQuestionAnswer;
import org.destecs.script.ast.expressions.ABoolSingleExp;


/**
* Generated file by AST Creator
* @author Kenneth Lausdahl
*
*/
public class ABoolSingleExp extends SSingleExpBase
{
	private static final long serialVersionUID = 1L;

	private Boolean _value;


	/**
	 * Creates a new {@link ABoolSingleExp} node with no children.
	 */
	public ABoolSingleExp()
	{

	}


	/**
	* Creates a new {@code ABoolSingleExp} node with the given nodes as children.
	* The basic child nodes are removed from their previous parents.
	* @param value_ the {@link Boolean} node for the {@code value} child of this {@link ABoolSingleExp} node
	*/
	public ABoolSingleExp(Boolean value_)
	{
		super();
		this.setValue(value_);

	}




	/**
	 * Essentially this.toString().equals(o.toString()).
	**/
	@Override
	public boolean equals(Object o) {
	if (o != null && o instanceof ABoolSingleExp)
	 return toString().equals(o.toString());
	return false; }
	

	public String toString()
	{
		return (_value!=null?_value.toString():this.getClass().getSimpleName());
	}


	/**
	 * Returns the {@link ESingleExp} corresponding to the
	 * type of this {@link ESingleExp} node.
	 * @return the {@link ESingleExp} for this node
	 */
	@Override
	public ESingleExp kindSSingleExp()
	{
		return ESingleExp.BOOL;
	}


	/**
	 * Returns a deep clone of this {@link ABoolSingleExp} node.
	 * @return a deep clone of this {@link ABoolSingleExp} node
	 */
	public ABoolSingleExp clone()
	{
		return new ABoolSingleExp(
			_value
		);
	}


	/**
	 * Removes the {@link INode} {@code child} as a child of this {@link ABoolSingleExp} node.
	 * Do not call this method with any graph fields of this node. This will cause any child's
	 * with the same reference to be removed unintentionally or {@link RuntimeException}will be thrown.
	 * @param child the child node to be removed from this {@link ABoolSingleExp} node
	 * @throws RuntimeException if {@code child} is not a child of this {@link ABoolSingleExp} node
	 */
	public void removeChild(INode child)
	{
		throw new RuntimeException("Not a child.");
	}


	/**
	 * Creates a deep clone of this {@link ABoolSingleExp} node while putting all
	 * old node-new node relations in the map {@code oldToNewMap}.
	 * @param oldToNewMap the map filled with the old node-new node relation
	 * @return a deep clone of this {@link ABoolSingleExp} node
	 */
	public ABoolSingleExp clone(Map<INode,INode> oldToNewMap)
	{
		ABoolSingleExp node = new ABoolSingleExp(
			_value
		);
		oldToNewMap.put(this, node);
		return node;
	}


	/**
	 * Sets the {@code _value} child of this {@link ABoolSingleExp} node.
	 * @param value the new {@code _value} child of this {@link ABoolSingleExp} node
	*/
	public void setValue(Boolean value)
	{
		this._value = value;
	}


	/**
	 * @return the {@link Boolean} node which is the {@code _value} child of this {@link ABoolSingleExp} node
	*/
	public Boolean getValue()
	{
		return this._value;
	}


	/**
	* Calls the {@link IAnalysis#caseABoolSingleExp(ABoolSingleExp)} of the {@link IAnalysis} {@code analysis}.
	* @param analysis the {@link IAnalysis} to which this {@link ABoolSingleExp} node is applied
	*/
	@Override
	public void apply(IAnalysis analysis)
	{
		analysis.caseABoolSingleExp(this);
	}


	/**
	* Calls the {@link IAnswer#caseABoolSingleExp(ABoolSingleExp)} of the {@link IAnswer} {@code caller}.
	* @param caller the {@link IAnswer} to which this {@link ABoolSingleExp} node is applied
	*/
	@Override
	public <A> A apply(IAnswer<A> caller)
	{
		return caller.caseABoolSingleExp(this);
	}


	/**
	* Calls the {@link IQuestion#caseABoolSingleExp(ABoolSingleExp, Object)} of the {@link IQuestion} {@code caller}.
	* @param caller the {@link IQuestion} to which this {@link ABoolSingleExp} node is applied
	* @param question the question provided to {@code caller}
	*/
	@Override
	public <Q> void apply(IQuestion<Q> caller, Q question)
	{
		caller.caseABoolSingleExp(this, question);
	}


	/**
	* Calls the {@link IQuestionAnswer#caseABoolSingleExp(ABoolSingleExp, Object)} of the {@link IQuestionAnswer} {@code caller}.
	* @param caller the {@link IQuestionAnswer} to which this {@link ABoolSingleExp} node is applied
	* @param question the question provided to {@code caller}
	*/
	@Override
	public <Q, A> A apply(IQuestionAnswer<Q, A> caller, Q question)
	{
		return caller.caseABoolSingleExp(this, question);
	}



}
